### ISSUE TITLE
The most recent cards are not displayed

### ISSUE THREAD

**Issue by olsson22** [JohnsonGlenT/Pazaak#16]
Issue found by Fredrik Olsson: The most recent played card is not visible
- the game will automatically deal a card to the player.
- the game will display that you have a card with a value in your hand.
- However, the card with the corresponding value is not displayed on the screen.
- As you play a card, the last played card will be displayed, but still, the most recently played card will not display.

**Comment by conn22** [comment]
Bug fixed: All cards are displayed correctly
